# Exploring NumPy
Playing with numpy methods and attributes

## Import NumPy

In [1]:
import numpy as np

## Data Types
Understanding arrays in numpy

In [2]:
# 1D array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
# 2D array
a2 = np.array([[1,2,3.1],
               [4,5,6.2],
               [7,8,9.3]])
a2

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2],
       [7. , 8. , 9.3]])

In [4]:
# 3D array
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[11,12,13],
                [14,15,16],
                [17,18,19]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [5]:
# shape of our arrays
a1.shape, a2.shape, a3.shape

((3,), (3, 3), (2, 3, 3))

In [6]:
# Dimensions of our arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
# DataTypes of our values in array
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

## Panads with NumPy
Creating Dataframe with numpy.ndarray

In [8]:
import pandas as pd

num_data = pd.DataFrame(a2)
num_data

0    1    2
0  1.0  2.0  3.1
1  4.0  5.0  6.2
2  7.0  8.0  9.3

## Creating arrays

In [9]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
zeros = np.zeros((3,3), dtype = int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
random = np.random.randint(0, 10, (3,3))

In [12]:
random

array([[2, 7, 2],
       [2, 4, 7],
       [0, 9, 5]])

In [13]:
random_1 = np.random.random((3,3,3))
random_1

array([[[0.94485417, 0.13004488, 0.37410421],
        [0.54000703, 0.81361195, 0.42943669],
        [0.1341188 , 0.35124571, 0.93369902]],

       [[0.70560099, 0.30246064, 0.28135252],
        [0.14791103, 0.44501136, 0.38359504],
        [0.95562704, 0.8841997 , 0.50934397]],

       [[0.91216413, 0.97064917, 0.67069222],
        [0.62335403, 0.34557431, 0.21350814],
        [0.06527215, 0.70242596, 0.11409149]]])

In [14]:
random_3 = np.random.rand(3,3)

In [15]:
random_3

array([[0.43105974, 0.11744272, 0.6844101 ],
       [0.8941647 , 0.84861715, 0.99119029],
       [0.56615455, 0.06894208, 0.11908765]])

In [16]:
# Prevents producing varying random numbers
np.random.seed(seed = 1)
random_4 = np.random.randint(10, 100, (3,3))
random_4

array([[47, 22, 82],
       [19, 85, 15],
       [89, 74, 26]])

## Viewing the elements of an array

In [17]:
# Return unique elemnts in an array
np.unique(random)

array([0, 2, 4, 5, 7, 9])

In [18]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.1],
        [4. , 5. , 6.2],
        [7. , 8. , 9.3]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]]))

In [19]:
# Slicing and accessing elements of the array
a1[0]

1

In [20]:
a2[0]

array([1. , 2. , 3.1])

In [21]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a2[0,1]

2.0

In [23]:
a3[0,1]

array([4, 5, 6])

In [24]:
a3[0,1,2]

6

In [25]:
a1[:2]

array([1, 2])

In [26]:
a2[:2]

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2]])

In [27]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [28]:
a2[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [29]:
a3[:2,:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [30]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 12],
        [14, 15]]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [32]:
# Return first 2 nums from third array in second matrix of a3
a3[1,2,:2]

array([17, 18])

## Manipulating Arrays

### Arithmetic