# Exploring NumPy
Playing with numpy methods and attributes

## Import NumPy

In [1]:
import numpy as np

## Data Types
Understanding arrays in numpy

In [2]:
# 1D array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
# 2D array
a2 = np.array([[1,2,3.1],
               [4,5,6.2],
               [7,8,9.3]])
a2

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2],
       [7. , 8. , 9.3]])

In [4]:
# 3D array
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[11,12,13],
                [14,15,16],
                [17,18,19]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [5]:
# shape of our arrays
a1.shape, a2.shape, a3.shape

((3,), (3, 3), (2, 3, 3))

In [6]:
# Dimensions of our arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
# DataTypes of our values in array
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

## Panads with NumPy
Creating Dataframe with numpy.ndarray

In [8]:
import pandas as pd

num_data = pd.DataFrame(a2)
num_data

0    1    2
0  1.0  2.0  3.1
1  4.0  5.0  6.2
2  7.0  8.0  9.3

## Creating arrays

In [9]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
zeros = np.zeros((3,3), dtype = int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
random = np.random.randint(0, 10, (3,3))
random

array([[2, 9, 7],
       [0, 9, 4],
       [1, 4, 4]])

In [12]:
random_1 = np.random.random((3,3,3))
random_1

array([[[0.30065946, 0.70301276, 0.63678636],
        [0.45375782, 0.52472616, 0.35875629],
        [0.70997755, 0.0714331 , 0.20887082]],

       [[0.832276  , 0.42304008, 0.67060928],
        [0.44045634, 0.07682596, 0.81620861],
        [0.36439204, 0.50075101, 0.48187572]],

       [[0.43132044, 0.56251658, 0.37346351],
        [0.4602513 , 0.95913396, 0.69491727],
        [0.97914186, 0.59318803, 0.9003056 ]]])

In [13]:
random_3 = np.random.rand(3,3)
random_3

array([[0.28654039, 0.61285966, 0.29679475],
       [0.75267341, 0.20608592, 0.41570277],
       [0.8824073 , 0.83425453, 0.62618057]])

In [14]:
# Prevents producing varying random numbers
np.random.seed(seed = 1)
random_4 = np.random.randint(10, 100, (3,3))
random_4

array([[47, 22, 82],
       [19, 85, 15],
       [89, 74, 26]])

## Viewing the elements of an array

In [15]:
# Return unique elemnts in an array
np.unique(random)

array([0, 1, 2, 4, 7, 9])

In [16]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.1],
        [4. , 5. , 6.2],
        [7. , 8. , 9.3]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]]))

In [17]:
# Slicing and accessing elements of the array
a1[0]

1

In [18]:
a2[0]

array([1. , 2. , 3.1])

In [19]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a2[0,1]

2.0

In [21]:
a3[0,1]

array([4, 5, 6])

In [22]:
a3[0,1,2]

6

In [23]:
a1[:2]

array([1, 2])

In [24]:
a2[:2]

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2]])

In [25]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [26]:
a2[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [27]:
a3[:2,:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [28]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 12],
        [14, 15]]])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [30]:
# Return first 2 nums from third array in second matrix of a3
a3[1,2,:2]

array([17, 18])

## Manipulating Arrays

### Arithmetic

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2],
       [7. , 8. , 9.3]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [35]:
ones = np.ones((3))

In [36]:
a1 + ones

array([2., 3., 4.])

In [37]:
a1 - ones

array([0., 1., 2.])

In [38]:
a1 * ones

array([1., 2., 3.])

In [39]:
a2 + a1

array([[ 2. ,  4. ,  6.1],
       [ 5. ,  7. ,  9.2],
       [ 8. , 10. , 12.3]])

In [40]:
a2 - a1

array([[0. , 0. , 0.1],
       [3. , 3. , 3.2],
       [6. , 6. , 6.3]])

In [41]:
a2 * a1

array([[ 1. ,  4. ,  9.3],
       [ 4. , 10. , 18.6],
       [ 7. , 16. , 27.9]])

In [42]:
a2 / a1

array([[1.        , 1.        , 1.03333333],
       [4.        , 2.5       , 2.06666667],
       [7.        , 4.        , 3.1       ]])

In [43]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.],
       [7., 4., 3.]])

In [44]:
a2 % a1

array([[0. , 0. , 0.1],
       [0. , 1. , 0.2],
       [0. , 0. , 0.3]])

In [45]:
a2 ** a1

array([[  1.   ,   4.   ,  29.791],
       [  4.   ,  25.   , 238.328],
       [  7.   ,  64.   , 804.357]])

In [52]:
a2[:2]

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2]])

In [53]:
# Explore Broadcasting in numpy
a3 * a2[:2]

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [54]:
a3 * a2

array([[[  1. ,   4. ,   9.3],
        [ 16. ,  25. ,  37.2],
        [ 49. ,  64. ,  83.7]],

       [[ 11. ,  24. ,  40.3],
        [ 56. ,  75. ,  99.2],
        [119. , 144. , 176.7]]])

In [55]:
# Reshape some_array so that it could be combined with a3
some_array = a2[:2]
some_array

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2]])

In [65]:
some_array = np.reshape(some_array, (2,1,3))
some_array

array([[[1. , 2. , 3.1]],

       [[4. , 5. , 6.2]]])

In [64]:
a3 * some_array

array([[[  1. ,   4. ,   9.3],
        [  4. ,  10. ,  18.6],
        [  7. ,  16. ,  27.9]],

       [[ 44. ,  60. ,  80.6],
        [ 56. ,  75. ,  99.2],
        [ 68. ,  90. , 117.8]]])

In [66]:
np.add(a1, a2)

array([[ 2. ,  4. ,  6.1],
       [ 5. ,  7. ,  9.2],
       [ 8. , 10. , 12.3]])

In [67]:
np.square(a1)

array([1, 4, 9], dtype=int32)

In [68]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [69]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [71]:
# Python's Methods vs NumPy's Methods

some_list = [1,2,3,4,5]
some_list

[1, 2, 3, 4, 5]

In [72]:
a1

array([1, 2, 3])

In [79]:
sum(some_list)

15

In [75]:
sum(a1)

6

In [76]:
np.sum(a1)

6

In [77]:
np.sum(some_list)

15

In [82]:
# Real Demonstration between Python and Numpy Aggregation
massive_array = np.random.rand(100000)
massive_array.size

100000

In [83]:
%timeit np.sum(massive_array) # Executon time NumPy's Method
%timeit sum(massive_array) # Executon time Python's Method

33 µs ± 425 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
5.98 ms ± 20.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Use `sum()` with Python DataTypes, use `numpy.sum()` with NumPy DataTypes

In [84]:
# Other Aggregation Methods of NumPy
np.mean(a1)

2.0

In [85]:
np.std(a1)

0.816496580927726

In [86]:
np.var(a1)

0.6666666666666666

In [87]:
np.sqrt(np.var(a1))

0.816496580927726