# Exploring NumPy
Playing with numpy methods and attributes

## Import NumPy

In [1]:
import numpy as np

## Data Types
Understanding arrays in numpy

In [2]:
# 1D array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
# 2D array
a2 = np.array([[1,2,3.1],
               [4,5,6.2],
               [7,8,9.3]])
a2

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2],
       [7. , 8. , 9.3]])

In [4]:
# 3D array
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[11,12,13],
                [14,15,16],
                [17,18,19]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [5]:
# shape of our arrays
a1.shape, a2.shape, a3.shape

((3,), (3, 3), (2, 3, 3))

In [6]:
# Dimensions of our arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
# DataTypes of our values in array
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

## Panads with NumPy
Creating Dataframe with `np.ndarray`

In [8]:
import pandas as pd

num_data = pd.DataFrame(a2)
num_data

0    1    2
0  1.0  2.0  3.1
1  4.0  5.0  6.2
2  7.0  8.0  9.3

## Creating arrays

In [9]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
zeros = np.zeros((3,3), dtype = int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
random = np.random.randint(0, 10, (3,3))
random

array([[1, 9, 9],
       [5, 4, 4],
       [9, 3, 6]])

In [12]:
random_1 = np.random.random((3,3,3))
random_1

array([[[0.16906189, 0.30829108, 0.05245618],
        [0.59846463, 0.447949  , 0.00896896],
        [0.99045795, 0.55578612, 0.85268337]],

       [[0.46484178, 0.48610753, 0.66137033],
        [0.5726104 , 0.61976693, 0.44439549],
        [0.44752657, 0.50835971, 0.96347597]],

       [[0.26161909, 0.1776507 , 0.79122195],
        [0.70898729, 0.34868279, 0.77222199],
        [0.75875496, 0.78678252, 0.98985393]]])

In [13]:
random_3 = np.random.rand(3,3)
random_3

array([[0.65100245, 0.55847867, 0.72599437],
       [0.48298851, 0.85758197, 0.33187063],
       [0.28617377, 0.49518333, 0.90309729]])

**Note**: ```np.random``` always produces pseudo random numbers

In [14]:
# Prevents producing varying random numbers
np.random.seed(seed = 1)
random_4 = np.random.randint(10, 100, (3,3))
random_4

array([[47, 22, 82],
       [19, 85, 15],
       [89, 74, 26]])

## Viewing the elements of an array

In [15]:
# Return unique elemnts in an array
np.unique(random)

array([1, 3, 4, 5, 6, 9])

In [16]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.1],
        [4. , 5. , 6.2],
        [7. , 8. , 9.3]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]]))

In [17]:
# Slicing and accessing elements of the array
a1[0]

1

In [18]:
a2[0]

array([1. , 2. , 3.1])

In [19]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a2[0,1]

2.0

In [21]:
a3[0,1]

array([4, 5, 6])

In [22]:
a3[0,1,2]

6

In [23]:
a1[:2]

array([1, 2])

In [24]:
a2[:2]

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2]])

In [25]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [26]:
a2[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [27]:
a3[:2,:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [28]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 12],
        [14, 15]]])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [30]:
# Return first 2 nums from third array in second matrix of a3
a3[1,2,:2]

array([17, 18])

## Manipulating Arrays

### Arithmetic

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2],
       [7. , 8. , 9.3]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [34]:
ones = np.ones((3))

In [35]:
a1 + ones

array([2., 3., 4.])

In [36]:
a1 - ones

array([0., 1., 2.])

In [37]:
a1 * ones

array([1., 2., 3.])

In [38]:
a2 + a1

array([[ 2. ,  4. ,  6.1],
       [ 5. ,  7. ,  9.2],
       [ 8. , 10. , 12.3]])

In [39]:
a2 - a1

array([[0. , 0. , 0.1],
       [3. , 3. , 3.2],
       [6. , 6. , 6.3]])

In [40]:
a2 * a1

array([[ 1. ,  4. ,  9.3],
       [ 4. , 10. , 18.6],
       [ 7. , 16. , 27.9]])

In [41]:
a2 / a1

array([[1.        , 1.        , 1.03333333],
       [4.        , 2.5       , 2.06666667],
       [7.        , 4.        , 3.1       ]])

In [42]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.],
       [7., 4., 3.]])

In [43]:
a2 % a1

array([[0. , 0. , 0.1],
       [0. , 1. , 0.2],
       [0. , 0. , 0.3]])

In [44]:
a2 ** a1

array([[  1.   ,   4.   ,  29.791],
       [  4.   ,  25.   , 238.328],
       [  7.   ,  64.   , 804.357]])

In [45]:
a2[:2]

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2]])

In [46]:
# Explore Broadcasting in numpy
a3 * a2[:2]

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [47]:
a3 * a2

array([[[  1. ,   4. ,   9.3],
        [ 16. ,  25. ,  37.2],
        [ 49. ,  64. ,  83.7]],

       [[ 11. ,  24. ,  40.3],
        [ 56. ,  75. ,  99.2],
        [119. , 144. , 176.7]]])

In [48]:
# Reshape some_array so that it could be combined with a3
some_array = a2[:2]
some_array

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2]])

In [49]:
some_array = np.reshape(some_array, (2,1,3))
some_array

array([[[1. , 2. , 3.1]],

       [[4. , 5. , 6.2]]])

In [50]:
a3 * some_array

array([[[  1. ,   4. ,   9.3],
        [  4. ,  10. ,  18.6],
        [  7. ,  16. ,  27.9]],

       [[ 44. ,  60. ,  80.6],
        [ 56. ,  75. ,  99.2],
        [ 68. ,  90. , 117.8]]])

In [51]:
np.add(a1, a2)

array([[ 2. ,  4. ,  6.1],
       [ 5. ,  7. ,  9.2],
       [ 8. , 10. , 12.3]])

In [52]:
np.square(a1)

array([1, 4, 9], dtype=int32)

In [53]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [54]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [55]:
# Python's Methods vs NumPy's Methods

some_list = [1,2,3,4,5]
some_list

[1, 2, 3, 4, 5]

In [56]:
a1

array([1, 2, 3])

In [58]:
sum(some_list)

15

In [59]:
sum(a1)

6

In [60]:
np.sum(a1)

6

In [61]:
np.sum(some_list)

15

In [62]:
# Real Demonstration between Python and Numpy Aggregation
massive_array = np.random.rand(100000)
massive_array.size

100000

In [63]:
%timeit np.sum(massive_array) # Executon time NumPy's Method
%timeit sum(massive_array) # Executon time Python's Method

39.2 µs ± 4.24 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
6.47 ms ± 36.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Use `sum()` with Python DataTypes, use `numpy.sum()` with NumPy DataTypes

In [64]:
# Other Aggregation Methods of NumPy
np.mean(a1)

2.0

In [65]:
np.std(a1)

0.816496580927726

In [66]:
np.var(a1)

0.6666666666666666

In [67]:
np.sqrt(np.var(a1))

0.816496580927726

In [68]:
np.min(a1)

1

In [69]:
np.max(a1)

3

## Tranpose
Revershing the dimensions of the array

In [70]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [71]:
a3.shape

(2, 3, 3)

In [72]:
a3.T

array([[[ 1, 11],
        [ 4, 14],
        [ 7, 17]],

       [[ 2, 12],
        [ 5, 15],
        [ 8, 18]],

       [[ 3, 13],
        [ 6, 16],
        [ 9, 19]]])

In [73]:
a3.T.shape

(3, 3, 2)

## Dot Product

In [74]:
matrixA = np.random.randint(0, 10, (2,3))
matrixB = np.random.randint(0, 10, (2,3))

In [75]:
matrixA

array([[3, 9, 7],
       [3, 5, 8]])

In [76]:
matrixB

array([[2, 6, 5],
       [9, 6, 6]])

In [77]:
# Element-wise multiplication
matrixA * matrixB

array([[ 6, 54, 35],
       [27, 30, 48]])

In [78]:
# Dot Product
# Matrix multiplication(similar to math)
np.dot(matrixA, matrixB)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [79]:
np.dot(matrixA, matrixB.T)

array([[ 95, 123],
       [ 76, 105]])

## Comparison

In [80]:
a2

array([[1. , 2. , 3.1],
       [4. , 5. , 6.2],
       [7. , 8. , 9.3]])

In [81]:
a2 > 1

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [82]:
some_array

array([[[1. , 2. , 3.1]],

       [[4. , 5. , 6.2]]])

In [83]:
a2 == some_array

array([[[ True,  True,  True],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [ True,  True,  True],
        [False, False, False]]])

In [84]:
a2 >= 5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

## Sorting

In [98]:
random_array = np.random.randint(0, 9, (3,3))

In [99]:
random_array

array([[4, 0, 2],
       [4, 6, 7],
       [5, 3, 5]])

In [93]:
np.sort(random_array)

array([[2, 2, 8],
       [2, 2, 3],
       [1, 2, 3]])

In [94]:
np.argsort(random_array)

array([[1, 2, 0],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [95]:
np.argmax(random_array)

0

In [102]:
np.argmax(random_array, axis = 1)

array([0, 2, 0], dtype=int64)

In [103]:
np.argmin(random_array, axis = 1)

array([1, 0, 1], dtype=int64)

## Image to Array

<img src="panda.png">

In [105]:
# To covert the above image into array
from matplotlib.image import imread

panda = imread("panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [106]:
panda.shape, panda.ndim, panda.size

((2330, 3500, 3), 3, 24465000)

## EOF